title: "CIERCMC – Université Paris Cité"
description: "Centre interdisciplinaire enseignement, recherche et création en milieu carcéral"

theme: null

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

navbar:
  - name: Accueil
    link: /
  - name: Équipe
    link: /pages/equipe.html
  - name: Projets
    link: /pages/projets.html
  - name: Publications
    link: /pages/publications.html
  - name: Partenaires
    link: /pages/partenaires.html
  - name: Contact
    link: /pages/contact.html
